### ISSUE TITLE
Check the render method of `unboundStoryFn`.

### ISSUE THREAD

**Issue by v9ai** [alepaez-dev/storybook-tailwindcss3#1]
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/1477453/185412999-5c10d579-8771-4965-bc04-0c9754324ab0.png">

**Comment by alepaez-dev** [comment]
A mistake with the imports, should be working now

**Comment by v9ai** [comment]
That was fast 🏎️ 
Thank you.
Keep up with great work.
